"""Pydantic request/response models, one module per domain area.

Re-exports every model at package level so the ~40 existing
`from ..schemas import X` imports across the app keep working unchanged —
the split is an internal reorganisation, not an API change.
"""

from __future__ import annotations

from .admin import (
    CorrectionOut,
    CoverageCandidateOut,
    CoverageGapOut,
    DismissedOut,
    EventDistrictIn,
    EventTrackIn,
    RawNoticeIn,
    RegroupOut,
    ReprocessApplyIn,
    ReprocessDayOut,
    ReprocessPreviewOut,
    ReprocessResultOut,
    ReprocessSummaryOut,
    ThreatTypeIn,
)
from .analytics import (
    DistrictStatOut,
    DurationBucketOut,
    HourBucketOut,
    JournalStatsOut,
    StatsDayOut,
    StatsTotalsOut,
)
from .auth import (
    AccessTokenOut,
    GoogleAuthIn,
    LoginIn,
    MeUpdateIn,
    RefreshIn,
    RegisterIn,
    TelegramAuthIn,
    TokenPairOut,
    UserOut,
)
from .base import _as_utc
from .bugs import (
    BugContextIn,
    BugReportAckOut,
    BugReporterOut,
    BugReportIn,
    BugReportOut,
    BugReportStatusIn,
)
from .common import (
    DistrictOut,
    SourceAdminOut,
    SourceDeleteOut,
    SourceIn,
    SourceLinkOut,
    SourceStatsOut,
    SourceUpdateIn,
)
from .friends import (
    ContactPrefIn,
    ContactPrefsOut,
    FriendActionOut,
    FriendOut,
    FriendRequestOut,
    FriendRequestsOut,
    FriendUserBrief,
    HomeIn,
    HomePointOut,
    HomeStyleIn,
    MyHomeOut,
    PresencePrefIn,
    PresencePrefOut,
    PublicUserBrief,
    SendFriendRequestIn,
    ShareToggleIn,
)
from .gamification import (
    AnalyzeIn,
    AnalyzeOut,
    CardCountOut,
    CollectionOut,
    GamificationPrefIn,
    GamificationPrefOut,
    ThreatAnalysisStateOut,
)
from .journal import (
    JournalAlertWindowOut,
    JournalDayOut,
    JournalOut,
)
from .push import (
    BrowserSubscriptionIn,
    HomeZoneIn,
    PushConfigOut,
    PushKeysIn,
    PushPrefsIn,
    PushPrefsOut,
    PushSubscribeIn,
    PushUnsubscribeIn,
)
from .raw import (
    RawCountOut,
    RawEventLinkOut,
    RawExportOut,
    RawLlmStatsOut,
    RawMessageOut,
    RawMessagesPage,
    RawParsedOut,
    RawSourceOut,
)
from .regions import (
    RegionAtOut,
    RegionOut,
)
from .situation import (
    AlertOut,
    AxisOut,
    IncidentOut,
    NoticeOut,
)
from .threats import (
    FeedEntryOut,
    ThreatEventOut,
    ThreatOut,
)
from .ws import (
    WSMessage,
)
from .zones import (
    AlertZoneOut,
)

__all__ = [
    "PresencePrefIn",
    "PresencePrefOut",
    "PublicUserBrief",
    "_as_utc",
    "AccessTokenOut",
    "AlertOut",
    "AlertZoneOut",
    "AnalyzeIn",
    "AnalyzeOut",
    "AxisOut",
    "BrowserSubscriptionIn",
    "BugContextIn",
    "BugReportAckOut",
    "BugReportIn",
    "BugReportOut",
    "BugReportStatusIn",
    "BugReporterOut",
    "CardCountOut",
    "CollectionOut",
    "CorrectionOut",
    "CoverageCandidateOut",
    "CoverageGapOut",
    "DismissedOut",
    "DistrictOut",
    "DistrictStatOut",
    "DurationBucketOut",
    "EventDistrictIn",
    "EventTrackIn",
    "FeedEntryOut",
    "FriendActionOut",
    "FriendOut",
    "FriendRequestOut",
    "FriendRequestsOut",
    "FriendUserBrief",
    "GamificationPrefIn",
    "GamificationPrefOut",
    "GoogleAuthIn",
    "HomePointOut",
    "HourBucketOut",
    "ContactPrefIn",
    "ContactPrefsOut",
    "HomeIn",
    "HomeStyleIn",
    "HomeZoneIn",
    "IncidentOut",
    "JournalAlertWindowOut",
    "JournalDayOut",
    "JournalOut",
    "JournalStatsOut",
    "LoginIn",
    "MeUpdateIn",
    "MyHomeOut",
    "NoticeOut",
    "PushConfigOut",
    "PushKeysIn",
    "PushPrefsIn",
    "PushPrefsOut",
    "PushSubscribeIn",
    "PushUnsubscribeIn",
    "RawCountOut",
    "RawEventLinkOut",
    "RawExportOut",
    "RawLlmStatsOut",
    "RawMessageOut",
    "RawMessagesPage",
    "RawParsedOut",
    "RawSourceOut",
    "RefreshIn",
    "RegionAtOut",
    "RegionOut",
    "RegisterIn",
    "RawNoticeIn",
    "ReprocessApplyIn",
    "ReprocessDayOut",
    "ReprocessPreviewOut",
    "ReprocessResultOut",
    "ReprocessSummaryOut",
    "SendFriendRequestIn",
    "ShareToggleIn",
    "SourceAdminOut",
    "SourceDeleteOut",
    "SourceIn",
    "SourceLinkOut",
    "SourceStatsOut",
    "SourceUpdateIn",
    "StatsDayOut",
    "StatsTotalsOut",
    "TelegramAuthIn",
    "ThreatAnalysisStateOut",
    "ThreatEventOut",
    "ThreatOut",
    "RegroupOut",
    "ThreatTypeIn",
    "TokenPairOut",
    "UserOut",
    "WSMessage",
]
