"""Gazetteer: every place the parser can put on the map.

Entry shape — `name_uk`, `name_en`, `lat`, `lon`, `aliases`, optional `region`
(default "kyiv") and optional `region_only`.

**Read `GAZETTEER.md` (repo root) before adding, changing or removing an entry.**
It holds what is not obvious from a line here: how the stemmer shapes a name
(and why so many entries need an alias), the mandatory geocode + corpus-sweep
procedure, the names deliberately NOT added and why, and the entries that ride
on a clean sweep and must be re-swept if the feed changes. A bad entry does not
crash — it puts a target on the wrong side of the country.

Comments below are only what you need while editing that specific line.
"""

from __future__ import annotations

# Re-exported: an entry with no `region` key defaults to it, and `app.parsing`
# reads it from here. Safe to import — the registry is ORM-free too.
from .regions import HOME_REGION as HOME_REGION

# name_en of the city-wide sentinel "district" (last entry). DistrictMatcher
# skips it so a real "київ" never over-matches; ingest attaches city-wide events
# to it.
CITYWIDE_NAME_EN = "Kyiv (citywide)"

# Initial map framing AND the sentinel district's coordinates.
KYIV_CENTER = {"lat": 50.4501, "lon": 30.5234}

DISTRICTS: list[dict] = [
    # "голос" is whole-word only (vocab._WHOLE_WORD_ALIASES): as a stem it fires
    # inside "голосно"/"голосування".
    {"name_uk": "Голосіївський", "name_en": "Holosiivskyi", "lat": 50.381, "lon": 30.508,
     "aliases": ["голосіїв", "голосіївський район", "голосієво", "голос"]},
    {"name_uk": "Дарницький", "name_en": "Darnytskyi", "lat": 50.410, "lon": 30.630,
     "aliases": ["дарниця", "дарницький район"]},
    {"name_uk": "Деснянський", "name_en": "Desnianskyi", "lat": 50.515, "lon": 30.605,
     "aliases": ["деснянський район"]},
    {"name_uk": "Дніпровський", "name_en": "Dniprovskyi", "lat": 50.455, "lon": 30.610,
     "aliases": ["дніпровський район"]},
    {"name_uk": "Оболонський", "name_en": "Obolonskyi", "lat": 50.520, "lon": 30.498,
     "aliases": ["оболонський район"]},
    {"name_uk": "Печерський", "name_en": "Pecherskyi", "lat": 50.425, "lon": 30.540,
     "aliases": ["печерськ", "печерський район"]},
    {"name_uk": "Подільський", "name_en": "Podilskyi", "lat": 50.470, "lon": 30.515,
     "aliases": ["поділ", "подільський район"]},
    # "солома" also means straw; swept clean, all 11 forms are this raion.
    {"name_uk": "Солом'янський", "name_en": "Solomianskyi", "lat": 50.430, "lon": 30.450,
     "aliases": ["солом'янка", "солом'янський район", "соломянський", "солома"]},
    {"name_uk": "Шевченківський", "name_en": "Shevchenkivskyi", "lat": 50.455, "lon": 30.470,
     "aliases": ["шевченківський район"]},
    {"name_uk": "Святошинський", "name_en": "Sviatoshynskyi", "lat": 50.455, "lon": 30.365,
     "aliases": ["святошино", "святошин", "святошинський район"]},


    # --- Kyiv microdistricts spotters name directly ---
    {"name_uk": "Троєщина", "name_en": "Troieshchyna", "lat": 50.515, "lon": 30.600,
     "aliases": ["троя", "трої", "трою", "троєю", "троєщино"]},
    {"name_uk": "Оболонь", "name_en": "Obolon", "lat": 50.510, "lon": 30.498,
     "aliases": ["оболонь"]},
    {"name_uk": "Позняки", "name_en": "Pozniaky", "lat": 50.397, "lon": 30.635,
     "aliases": ["позняки"]},
    {"name_uk": "Осокорки", "name_en": "Osokorky", "lat": 50.400, "lon": 30.610,
     "aliases": ["осокорки"]},
    # Case forms spelled out: the 4-char stem floor keeps "пущ" out (it would fire
    # on "Пущено ракети") and "пуща"+tail cannot reach "Пущею"/"Пущі".
    {"name_uk": "Пуща-Водиця", "name_en": "PushchaVodytsia", "lat": 50.5371, "lon": 30.3564,
     "aliases": ["пуща", "пущі", "пущу", "пущею", "пуща водиця", "пущаводиця"]},
    {"name_uk": "Виноградар", "name_en": "Vynohradar", "lat": 50.500, "lon": 30.415,
     "aliases": ["виноградар"]},
    # "антонов" = the Antonov plant, whole-word only — as a stem it ate the
    # Chernihiv village Антоновичі (which now has its own entry).
    {"name_uk": "Нивки", "name_en": "Nyvky", "lat": 50.460, "lon": 30.410,
     "aliases": ["нивки", "антонов", "антонова"]},
    {"name_uk": "Борщагівка", "name_en": "Borshchahivka", "lat": 50.435, "lon": 30.375,
     "aliases": ["борщагівка", "борщага"]},
    {"name_uk": "Теремки", "name_en": "Teremky", "lat": 50.360, "lon": 30.455,
     "aliases": ["теремки"]},
    {"name_uk": "Деміївка", "name_en": "Demiivka", "lat": 50.404, "lon": 30.5159,
     "aliases": []},
    {"name_uk": "Іподром", "name_en": "Ippodrom", "lat": 50.3766, "lon": 30.469,
     "aliases": []},
    {"name_uk": "Совки", "name_en": "Sovky", "lat": 50.4062, "lon": 30.4852,
     "aliases": []},
    # Whole-word only: the stem is a prefix of "центральній", "укргідрометцентр".
    # Point is Хрещатик, which is what a spotter means by "центр".
    {"name_uk": "Центр", "name_en": "KyivCentre", "lat": 50.4472, "lon": 30.5229,
     "aliases": ["центру", "центрі"]},
    {"name_uk": "Русанівка", "name_en": "Rusanivka", "lat": 50.440, "lon": 30.590,
     "aliases": ["русанівка"]},
    {"name_uk": "Бортничі", "name_en": "Bortnychi", "lat": 50.395, "lon": 30.700,
     "aliases": ["бортничі"]},
    {"name_uk": "ДВРЗ", "name_en": "DVRZ", "lat": 50.445, "lon": 30.660,
     "aliases": ["дврз"]},
    {"name_uk": "Лівобережний", "name_en": "Livoberezhnyi", "lat": 50.452, "lon": 30.598,
     "aliases": ["лівий берег", "лівобережна"]},

    {"name_uk": "Сирець", "name_en": "Syrets", "lat": 50.478, "lon": 30.430,
     "aliases": ["сирця", "сирці"]},
    {"name_uk": "Почайна", "name_en": "Pochaina", "lat": 50.485, "lon": 30.500,
     "aliases": ["почайни"]},
    {"name_uk": "Наталка", "name_en": "Natalka", "lat": 50.522, "lon": 30.508,
     "aliases": []},
    {"name_uk": "Лук'янівка", "name_en": "Lukianivka", "lat": 50.473, "lon": 30.470,
     "aliases": ["лукянівка"]},
    {"name_uk": "Чоколівка", "name_en": "Chokolivka", "lat": 50.425, "lon": 30.440,
     "aliases": []},
    {"name_uk": "Отрадний", "name_en": "Otradnyi", "lat": 50.453, "lon": 30.418,
     "aliases": ["відрадний"]},
    {"name_uk": "Академмістечко", "name_en": "Akademmistechko", "lat": 50.464, "lon": 30.363,
     "aliases": ["академ"]},
    {"name_uk": "Феофанія", "name_en": "Feofaniia", "lat": 50.343, "lon": 30.487,
     "aliases": []},
    {"name_uk": "Березняки", "name_en": "Berezniaky", "lat": 50.418, "lon": 30.600,
     "aliases": []},
    {"name_uk": "Воскресенка", "name_en": "Voskresenka", "lat": 50.470, "lon": 30.590,
     "aliases": []},
    {"name_uk": "Микільська Слобідка", "name_en": "Nykilska Slobidka", "lat": 50.452, "lon": 30.578,
     "aliases": ["слобідка"]},
    {"name_uk": "Вигурівщина", "name_en": "Vyhurivshchyna", "lat": 50.4985, "lon": 30.6018,
     "aliases": []},
    {"name_uk": "Видубичі", "name_en": "Vydubychi", "lat": 50.4147, "lon": 30.568,
     "aliases": []},
    # ТЕЦ-5 and ТЕЦ-6 are DIFFERENT plants 12 km apart, so both carry numbered
    # forms only. A bare "тец" alias was tried 2026-08-21 and reverted (GAZETTEER.md).
    {"name_uk": "ТЕЦ-5", "name_en": "TETs-5 (CHP-5)", "lat": 50.3942, "lon": 30.5684,
     "aliases": ["тец-5", "тец5", "тэц-5", "тэц5"]},
    {"name_uk": "ТЕЦ-6", "name_en": "TETs-6 (CHP-6)", "lat": 50.5312, "lon": 30.667,
     "aliases": ["тец-6", "тец6", "тэц-6", "тэц6"]},


    # --- Approach-corridor localities, Kyiv oblast ---
    {"name_uk": "Макарів", "name_en": "Makariv", "lat": 50.463, "lon": 29.812,
     "aliases": ["макарова", "макарову"]},
    {"name_uk": "Буча", "name_en": "Bucha", "lat": 50.545, "lon": 30.213,
     "aliases": ["бучі", "бучу"]},
    {"name_uk": "Ірпінь", "name_en": "Irpin", "lat": 50.522, "lon": 30.250,
     "aliases": ["ірпеня", "ірпені"]},
    {"name_uk": "Гостомель", "name_en": "Hostomel", "lat": 50.575, "lon": 30.266,
     "aliases": ["гостомеля"]},
    {"name_uk": "Бузова", "name_en": "Buzova", "lat": 50.423, "lon": 30.020,
     "aliases": ["бузової", "бузову"]},
    {"name_uk": "Чайки", "name_en": "Chaiky", "lat": 50.393, "lon": 30.302,
     "aliases": ["чайках"]},
    {"name_uk": "Вишневе", "name_en": "Vyshneve", "lat": 50.386, "lon": 30.372,
     "aliases": ["вишневого", "вишня", "вишню"]},
    {"name_uk": "Вишгород", "name_en": "Vyshhorod", "lat": 50.585, "lon": 30.490,
     "aliases": ["вишгорода"]},
    {"name_uk": "Бровари", "name_en": "Brovary", "lat": 50.511, "lon": 30.790,
     "aliases": ["броварів", "броварський", "торгмаш"]},
    {"name_uk": "Бориспіль", "name_en": "Boryspil", "lat": 50.353, "lon": 30.955,
     "aliases": ["борисполя"]},
    {"name_uk": "Васильків", "name_en": "Vasylkiv", "lat": 50.185, "lon": 30.315,
     "aliases": ["василькова", "васік", "васик"]},
    {"name_uk": "Обухів", "name_en": "Obukhiv", "lat": 50.107, "lon": 30.615,
     "aliases": ["обухова"]},
    {"name_uk": "Фастів", "name_en": "Fastiv", "lat": 50.078, "lon": 29.910,
     "aliases": ["фастова"]},
    {"name_uk": "Наливайківка", "name_en": "Nalyvaikivka", "lat": 50.484, "lon": 29.711,
     "aliases": ["наливайківку", "наливайківки"]},
    {"name_uk": "Трипілля", "name_en": "Trypillia", "lat": 50.115, "lon": 30.777,
     "aliases": ["трипілля", "трипільськ"]},

    # Administratively Kyiv oblast, but 150 km north — `region` follows geography,
    # because it decides which track pool a sighting joins.
    {"name_uk": "Славутич", "name_en": "Slavutych", "lat": 51.519, "lon": 30.746,
     "region": "chernihiv", "aliases": ["славутича", "славутичі"]},
    {"name_uk": "Десна", "name_en": "Desna", "lat": 50.9248, "lon": 30.773,
     "region": "chernihiv", "aliases": ["десну", "десни"]},
    {"name_uk": "Жукин", "name_en": "Zhukyn", "lat": 50.716, "lon": 30.628,
     "aliases": ["жукина", "жукині"]},
    {"name_uk": "Боденьки", "name_en": "Bodenky", "lat": 50.740, "lon": 30.590,
     "aliases": ["боденьок"]},
    {"name_uk": "Кіпті", "name_en": "Kipti", "lat": 51.147, "lon": 31.305,
     "region": "chernihiv", "aliases": ["кіптях", "кіптів", "кіптями"]},

    {"name_uk": "Осещина", "name_en": "Oseshchyna", "lat": 50.5756, "lon": 30.5478,
     "aliases": []},
    {"name_uk": "Погреби", "name_en": "Pohreby", "lat": 50.5546, "lon": 30.6425,
     "aliases": []},
    {"name_uk": "Зазимʼя", "name_en": "Zazymia", "lat": 50.5739, "lon": 30.6749,
     "aliases": []},
    {"name_uk": "Пухівка", "name_en": "Pukhivka", "lat": 50.5909, "lon": 30.7169,
     "aliases": []},
    {"name_uk": "Рожни", "name_en": "Rozhny", "lat": 50.6707, "lon": 30.741,
     "aliases": []},
    {"name_uk": "Пірнове", "name_en": "Pirnove", "lat": 50.7528, "lon": 30.6686,
     "aliases": []},
    {"name_uk": "Лебедівка", "name_en": "Lebedivka", "lat": 50.7137, "lon": 30.5446,
     "aliases": []},


    # --- Approach ring around Kyiv, grouped by threat axis ---
    {"name_uk": "Козелець", "name_en": "Kozelets", "lat": 50.9161, "lon": 31.1168,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Калита", "name_en": "Kalyta", "lat": 50.7499, "lon": 31.0249, "aliases": []},
    {"name_uk": "Семиполки", "name_en": "Semypolky", "lat": 50.7235, "lon": 30.9461, "aliases": []},
    {"name_uk": "Літки", "name_en": "Litky", "lat": 50.7069, "lon": 30.743, "aliases": []},
    {"name_uk": "Богданівка", "name_en": "Bohdanivka", "lat": 50.625, "lon": 30.9138, "aliases": []},
    {"name_uk": "Димер", "name_en": "Dymer", "lat": 50.7864, "lon": 30.3039, "aliases": []},
    # The alias IS the entry: a spaced name never becomes one stem, and "димерка"
    # is what spotters write. Twin of the Chernihiv Димерка below.
    {"name_uk": "Велика Димерка", "name_en": "Velyka Dymerka", "lat": 50.5914, "lon": 30.9016,
     "aliases": ["димерка"]},
    {"name_uk": "Демидів", "name_en": "Demydiv", "lat": 50.7277, "lon": 30.3306, "aliases": []},
    {"name_uk": "Козаровичі", "name_en": "Kozarovychi", "lat": 50.7561, "lon": 30.3519, "aliases": []},
    {"name_uk": "Катюжанка", "name_en": "Katiuzhanka", "lat": 50.8034, "lon": 30.1338, "aliases": []},
    {"name_uk": "Переяслав", "name_en": "Pereiaslav", "lat": 50.0644, "lon": 31.4447, "aliases": []},
    {"name_uk": "Яготин", "name_en": "Yahotyn", "lat": 50.2759, "lon": 31.7635, "aliases": []},
    {"name_uk": "Баришівка", "name_en": "Baryshivka", "lat": 50.3645, "lon": 31.3257, "aliases": []},
    # Stems to "березан", a prefix of the Chernihiv «Березанка» — see that entry.
    {"name_uk": "Березань", "name_en": "Berezan", "lat": 50.3133, "lon": 31.4689, "aliases": []},
    {"name_uk": "Гоголів", "name_en": "Hoholiv", "lat": 50.5127, "lon": 31.0226, "aliases": []},
    {"name_uk": "Требухів", "name_en": "Trebukhiv", "lat": 50.4833, "lon": 30.9011, "aliases": []},
    {"name_uk": "Княжичі", "name_en": "Kniazhychi", "lat": 50.4604, "lon": 30.7862, "aliases": []},
    {"name_uk": "Боярка", "name_en": "Boiarka", "lat": 50.3357, "lon": 30.2848, "aliases": []},
    {"name_uk": "Глеваха", "name_en": "Hlevakha", "lat": 50.2597, "lon": 30.3059, "aliases": []},
    {"name_uk": "Крюківщина", "name_en": "Kriukivshchyna", "lat": 50.3719, "lon": 30.3716, "aliases": []},
    {"name_uk": "Гатне", "name_en": "Hatne", "lat": 50.3585, "lon": 30.3963, "aliases": []},
    {"name_uk": "Білогородка", "name_en": "Bilohorodka", "lat": 50.3772, "lon": 30.2837, "aliases": []},
    # On the Zhytomyr highway west of the city, in a real hole — the nearest
    # entry was Ірпінь, 7.8 km away. Four different channels name it.
    # The obvious collider «автостоянка» cannot fire: the matcher anchors on a
    # word start. The bare noun («стоянка таксі») could, and is zero for zero
    # across the corpus — watch-listed in GAZETTEER.md rather than assumed safe.
    {"name_uk": "Стоянка", "name_en": "Stoianka", "lat": 50.454, "lon": 30.2261, "aliases": []},
    {"name_uk": "Ржищів", "name_en": "Rzhyshchiv", "lat": 49.9682, "lon": 31.0412, "aliases": []},
    {"name_uk": "Козин", "name_en": "Kozyn", "lat": 50.229, "lon": 30.6479, "aliases": []},
    # "церкв" requires a preceding "Біл…" (vocab._ALIAS_PREV_WORD_REQUIRED), or
    # "приліт у церкву" pins a strike 80 km out of town. "бц" is whole-word.
    {"name_uk": "Біла Церква", "name_en": "BilaTserkva", "lat": 49.797, "lon": 30.1158,
     "aliases": ["церкв", "білоцерк", "бц"]},
    {"name_uk": "Рокитне", "name_en": "Rokytne", "lat": 49.6867, "lon": 30.473, "aliases": []},
    {"name_uk": "Тараща", "name_en": "Tarashcha", "lat": 49.5555, "lon": 30.5023, "aliases": []},
    {"name_uk": "Богуслав", "name_en": "Bohuslav", "lat": 49.5476, "lon": 30.8733, "aliases": []},
    {"name_uk": "Миронівка", "name_en": "Myronivka", "lat": 49.6583, "lon": 30.9825, "aliases": []},
    {"name_uk": "Кагарлик", "name_en": "Kaharlyk", "lat": 49.8651, "lon": 30.8227, "aliases": []},
    {"name_uk": "Бородянка", "name_en": "Borodianka", "lat": 50.6438, "lon": 29.9278, "aliases": []},
    {"name_uk": "Немішаєве", "name_en": "Nemishaieve", "lat": 50.568, "lon": 30.1015, "aliases": []},
    {"name_uk": "Клавдієво", "name_en": "Klavdiieve", "lat": 50.5841, "lon": 30.0095,
     "aliases": ["клавдієво-тарасове"]},
    {"name_uk": "Іванків", "name_en": "Ivankiv", "lat": 50.933, "lon": 29.9043, "aliases": []},
    {"name_uk": "Пісківка", "name_en": "Piskivka", "lat": 50.6969, "lon": 29.5931, "aliases": []},
    # Oblique cases carry an і→е alternation the stemmer cannot bridge.
    {"name_uk": "Бишів", "name_en": "Byshiv", "lat": 50.2666, "lon": 29.8869,
     "aliases": ["бишева", "бишеві"]},


    # --- In-city micro-neighbourhoods and landmarks ---
    {"name_uk": "Труханів острів", "name_en": "TrukhanivIsland", "lat": 50.4852, "lon": 30.5484,
     "aliases": ["труханів", "труханова"]},
    {"name_uk": "Гідропарк", "name_en": "Hidropark", "lat": 50.4385, "lon": 30.5796, "aliases": []},
    {"name_uk": "Контрактова площа", "name_en": "KontraktovaSquare", "lat": 50.4627, "lon": 30.5184,
     "aliases": ["контрактова"]},
    {"name_uk": "Липки", "name_en": "Lypky", "lat": 50.4449, "lon": 30.5331, "aliases": []},
    {"name_uk": "Клов", "name_en": "Klov", "lat": 50.44, "lon": 30.5346, "aliases": []},
    {"name_uk": "Куренівка", "name_en": "Kurenivka", "lat": 50.4885, "lon": 30.4703, "aliases": []},
    {"name_uk": "Пріорка", "name_en": "Priorka", "lat": 50.5047, "lon": 30.4525, "aliases": []},
    {"name_uk": "Мінський масив", "name_en": "MinskyiMasyv", "lat": 50.5192, "lon": 30.4619,
     "aliases": ["мінський"]},
    {"name_uk": "Шулявка", "name_en": "Shuliavka", "lat": 50.45, "lon": 30.444, "aliases": []},
    {"name_uk": "Теличка", "name_en": "Telychka", "lat": 50.3956, "lon": 30.5711, "aliases": []},
    {"name_uk": "Харківський масив", "name_en": "KharkivskyiMasyv", "lat": 50.4118, "lon": 30.6581,
     "aliases": ["харківський"]},
    # ONE entry at the three massifs' centroid, not an alias on all three: three ids
    # for one callout would read as three simultaneous targets. Whole-word only.
    {"name_uk": "Позняки-Осокорки-Харківський", "name_en": "PoznyakyOsokorkyKharkivskyi",
     "lat": 50.4029, "lon": 30.6363, "aliases": ["пох"]},
    {"name_uk": "Русанівські сади", "name_en": "RusanivskiSady", "lat": 50.4744, "lon": 30.5753,
     "aliases": []},
    {"name_uk": "Нижні Сади", "name_en": "NyzhniSady", "lat": 50.3682, "lon": 30.6076, "aliases": []},
    {"name_uk": "Лісовий масив", "name_en": "LisovyiMasyv", "lat": 50.4746, "lon": 30.6302,
     "aliases": ["лісовий"]},
    {"name_uk": "Жуляни", "name_en": "Zhuliany", "lat": 50.3928, "lon": 30.4422, "aliases": []},
    {"name_uk": "Биківня", "name_en": "Bykivnia", "lat": 50.476, "lon": 30.6705, "aliases": []},
    {"name_uk": "Вокзальна площа", "name_en": "VokzalnaSquare", "lat": 50.4406, "lon": 30.4901,
     "aliases": ["вокзальна"]},


    # --- Villages/settlements near Kyiv ---
    {"name_uk": "Ворзель", "name_en": "Vorzel", "lat": 50.5457, "lon": 30.1563, "aliases": []},
    {"name_uk": "Воропаїв", "name_en": "Voropaiv", "lat": 50.7692, "lon": 30.6582, "aliases": []},
    {"name_uk": "Вишеньки", "name_en": "Vyshenky", "lat": 50.3043, "lon": 30.7147, "aliases": []},
    {"name_uk": "Кийлів", "name_en": "Kyiliv", "lat": 50.1485, "lon": 30.8845, "aliases": []},
    {"name_uk": "Гнідин", "name_en": "Hnidyn", "lat": 50.3287, "lon": 30.7058, "aliases": []},
    {"name_uk": "Горенка", "name_en": "Horenka", "lat": 50.5596, "lon": 30.3123, "aliases": []},
    {"name_uk": "Хотянівка", "name_en": "Khotianivka", "lat": 50.5959, "lon": 30.5668, "aliases": []},
    # Kyiv oblast has several; all stored mentions are this one — the Desna
    # left-bank approach, named together with Хотянівка and Зазимʼя.
    {"name_uk": "Новосілки", "name_en": "Novosilky", "lat": 50.612, "lon": 30.6304,
     "aliases": []},
    {"name_uk": "Чабани", "name_en": "Chabany", "lat": 50.3414, "lon": 30.4271, "aliases": []},
    # Also means "happy" — kept on a clean sweep only. See GAZETTEER.md (watch list).
    {"name_uk": "Щасливе", "name_en": "Shchaslyve", "lat": 50.3782, "lon": 30.7913, "aliases": []},
    {"name_uk": "Згурівка", "name_en": "Zghurivka", "lat": 50.4951, "lon": 31.7692, "aliases": []},
    {"name_uk": "Ходосівка", "name_en": "Khodosivka", "lat": 50.2728, "lon": 30.5221, "aliases": []},
    # The bare «Заспа» rides here as an ALIAS rather than as its own entry —
    # there is a second Заспа ~45 km south, and a standalone record would have
    # to put a point on one of them. As an alias no new point exists.
    # заспа/заспу/заспи are WHOLE-WORD (vocab._WHOLE_WORD_ALIASES): as stems
    # they fire inside «заспокоїтись», which is the collision that kept this
    # name out for the life of the project. See GAZETTEER.md.
    {"name_uk": "Конча-Заспа", "name_en": "KonchaZaspa", "lat": 50.3007, "lon": 30.5765,
     "aliases": ["конча", "заспа", "заспу", "заспи"]},
    # Stem "рогоз" is also the cattail plant — clean sweep only (watch list).
    {"name_uk": "Рогозів", "name_en": "Rohoziv", "lat": 50.2339, "lon": 31.055, "aliases": []},
    # Stem "пирог" is also пироги/пиріг — clean sweep only (watch list).
    {"name_uk": "Пирогів", "name_en": "Pyrohiv", "lat": 50.3545, "lon": 30.5145, "aliases": []},
    # Point HAND-SET: Nominatim resolves this name to a homonym ~350 km away.
    # Do not "fix" it by re-geocoding.
    {"name_uk": "Чапаївка", "name_en": "Chapaivka", "lat": 50.343, "lon": 30.522, "aliases": []},
    # Hyphenated compound only — bare "Віта" collides with вітаю/вітання.
    {"name_uk": "Віта-Поштова", "name_en": "VitaPoshtova", "lat": 50.3197, "lon": 30.3809, "aliases": []},
    # "трипіл" covers both the plant and the village 2 km away (same target cluster).
    {"name_uk": "Трипільська ТЕС", "name_en": "Trypilska TES", "lat": 50.1333, "lon": 30.75,
     "aliases": ["трипілля", "трипільська", "трипіл"]},
    {"name_uk": "Київське водосховище", "name_en": "KyivReservoir", "lat": 50.9218, "lon": 30.5047,
     "aliases": ["водосховище"]},
    # Deliberately a SEPARATE, nearer point than KyivReservoir above: "район моря"
    # means the near edge of the water, the corridor into the city. The only false
    # hit ("Чорного моря" in bomber reports) is vetoed by matcher._is_foreign_sea.
    {"name_uk": "Район моря", "name_en": "KyivSeaApproach", "lat": 50.66, "lon": 30.52,
     "aliases": ["море", "моря", "морі"]},

    # "чзв" is 3 chars — below the stem floor, so it needs _WHOLE_WORD_ALIASES.
    {"name_uk": "Чорнобильська зона", "name_en": "ChornobylZone", "lat": 51.2705, "lon": 30.2196,
     "aliases": ["чзв", "чорнобиль"]},
    {"name_uk": "Страхолісся", "name_en": "Strakholissia", "lat": 51.0755, "lon": 30.395,
     "aliases": []},



    # --- Чернігівщина: the northern approach corridor ---
    # "ліюбеч" is a real typo the channel makes mid-callout.
    {"name_uk": "Любеч", "name_en": "Liubech", "lat": 51.7005, "lon": 30.6587,
     "region": "chernihiv", "aliases": ["ліюбеч"]},
    # The other half of the Нивки/"антонов" fix — the place those messages meant.
    {"name_uk": "Антоновичі", "name_en": "Antonovychi", "lat": 51.5791, "lon": 30.9251,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Остер", "name_en": "Oster", "lat": 50.9508, "lon": 30.8782,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Городня", "name_en": "Horodnia", "lat": 51.8915, "lon": 31.5955,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Гончарівське", "name_en": "Honcharivske", "lat": 51.299, "lon": 30.9276,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хрінівка", "name_en": "Khrinivka", "lat": 52.0691, "lon": 31.8401,
     "region": "chernihiv", "aliases": []},
    # Genitive plural drops и and inserts о INSIDE the root; the stemmer only strips
    # endings, so "ріпок" needs to be spelled out.
    {"name_uk": "Ріпки", "name_en": "Ripky", "lat": 51.8036, "lon": 31.0931,
     "region": "chernihiv", "aliases": ["ріпок"]},
    {"name_uk": "Сеньківка", "name_en": "Senkivka", "lat": 52.1064, "lon": 31.7809,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Будище", "name_en": "Budyshche", "lat": 51.3024, "lon": 30.77,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Седнів", "name_en": "Sedniv", "lat": 51.6421, "lon": 31.5624,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Олешня", "name_en": "Oleshnia", "lat": 51.9459, "lon": 31.1714,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Морівськ", "name_en": "Morivsk", "lat": 51.0923, "lon": 30.8675,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Лошакова Гута", "name_en": "Loshakova Huta", "lat": 51.0291, "lon": 30.656,
     "region": "chernihiv", "aliases": ["лошакова", "лошакову"]},
    # The channel's plural «Гути» rides here. It means the Василева/Хатилова
    # pair 2.3 km apart, NOT Лошакова Гута 30 km south: the corridor bulletin
    # (raw 6589) lists «…Славутич/Неданчичі ➡️ Боровики/Гути ➡️ Десна/Остер»,
    # and Боровики is 2.1 km from here while Лошакова belongs to the NEXT stage
    # (14 km from Десна). Whole-word (vocab._WHOLE_WORD_ALIASES) — 4 letters is
    # too short to stem. Worst case it lands 2.3 km off, on its own neighbour.
    {"name_uk": "Василева Гута", "name_en": "Vasyleva Huta", "lat": 51.288, "lon": 30.7064,
     "region": "chernihiv", "aliases": ["василева", "василеву", "гути"]},
    {"name_uk": "Чудівка", "name_en": "Chudivka", "lat": 51.8765, "lon": 30.9985,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хотівля", "name_en": "Khotivlia", "lat": 51.9585, "lon": 31.5016,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Сорокошичі", "name_en": "Sorokoshychi", "lat": 51.1916, "lon": 30.6344,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Носівка", "name_en": "Nosivka", "lat": 50.9378, "lon": 31.5812,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ловинь", "name_en": "Lovyn", "lat": 51.8908, "lon": 31.1857,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Косачівка", "name_en": "Kosachivka", "lat": 51.1019, "lon": 30.6453,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Гірськ", "name_en": "Hirsk", "lat": 52.0186, "lon": 31.8535,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Грабів", "name_en": "Hrabiv", "lat": 51.8395, "lon": 30.9721,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Боровики", "name_en": "Borovyky", "lat": 51.2962, "lon": 30.7339,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Старосілля", "name_en": "Starosillia", "lat": 52.01, "lon": 31.6259,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Рівнопілля", "name_en": "Rivnopillia", "lat": 51.6067, "lon": 31.2331,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Рудня", "name_en": "Rudnia", "lat": 51.5677, "lon": 30.733,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Отрохи", "name_en": "Otrokhy", "lat": 51.1026, "lon": 30.8204,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Олишівка", "name_en": "Olyshivka", "lat": 51.2179, "lon": 31.3299,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ніжин", "name_en": "Nizhyn", "lat": 51.0465, "lon": 31.8806,
     "region": "chernihiv", "aliases": []},
    # Bare "новгород" is how the channel shortens it; the hyphenated stem cannot
    # reach that form.
    {"name_uk": "Новгород-Сіверський", "name_en": "Novhorod-Siverskyi", "lat": 52.0043, "lon": 33.278,
     "region": "chernihiv", "aliases": ["новгород-сіверськ", "новгород"]},
    {"name_uk": "Рогівка", "name_en": "Rohivka", "lat": 52.1603, "lon": 33.3102,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Леньків", "name_en": "Lenkiv", "lat": 52.0731, "lon": 33.2637,
     "region": "chernihiv", "aliases": []},
    # Beats Kyiv's Пирогів on stem length. The alias carries the і↔о alternation.
    {"name_uk": "Пирогівці", "name_en": "Pyrohivtsi", "lat": 50.6205, "lon": 32.3506,
     "region": "chernihiv", "aliases": ["пироговці"]},
    {"name_uk": "Обухове", "name_en": "Obukhove", "lat": 50.8483, "lon": 33.0297,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Понори", "name_en": "Ponory", "lat": 50.9264, "lon": 33.1148,
     "region": "chernihiv", "aliases": []},
    # Exists BECAUSE of Понори above: "понор" is a prefix of it, so without an entry
    # of its own «На понорницю» landed on a village 90 km south.
    {"name_uk": "Понорниця", "name_en": "Ponornytsia", "lat": 51.7205, "lon": 32.844,
     "region": "chernihiv", "aliases": []},
    # True homonym of Kyiv-oblast Велика Димерка — `prefer_region` separates them.
    # Adding either side alone hijacks the other.
    {"name_uk": "Димерка", "name_en": "Dymerka", "lat": 51.0699, "lon": 31.0659,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мрин", "name_en": "Mryn", "lat": 51.0544, "lon": 31.5414,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мощенка", "name_en": "Moshchenka", "lat": 52.0302, "lon": 31.7395,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Куликівка", "name_en": "Kulykivka", "lat": 51.3736, "lon": 31.6456,
     "region": "chernihiv", "aliases": []},
    # Two neighbours of Куликівка, 4.5 km apart, added together: they arrived 9 s
    # apart as one target walked between them and BOTH matched nothing.
    {"name_uk": "Глузди", "name_en": "Hluzdy", "lat": 51.4776, "lon": 31.6213,
     "region": "chernihiv", "aliases": []},
    # HOMONYM: the other Горбове is 115 km away in Новгород-Сіверський (51.94,
    # 33.22). This is the Куликівка one — its callout came 9 s after Глузди,
    # 4.5 km away, and the neighbours decide (GAZETTEER.md step 1).
    {"name_uk": "Горбове", "name_en": "Horbove", "lat": 51.4572, "lon": 31.5626,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кратинь", "name_en": "Kratyn", "lat": 51.7806, "lon": 30.8425,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Вертіївка", "name_en": "Vertiivka", "lat": 51.1637, "lon": 31.8483,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Борзна", "name_en": "Borzna", "lat": 51.2534, "lon": 32.4263,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бобровиця", "name_en": "Bobrovytsia", "lat": 50.7415, "lon": 31.3861,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дідівці", "name_en": "Didivtsi", "lat": 50.5848, "lon": 32.4758,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Голубівка", "name_en": "Holubivka", "lat": 50.5581, "lon": 32.492,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Плиски", "name_en": "Plysky", "lat": 51.1133, "lon": 32.4311,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Талалаївка", "name_en": "Talalaivka", "lat": 50.8317, "lon": 33.1344,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Вербівка", "name_en": "Verbivka", "lat": 52.0257, "lon": 31.2314,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бахмач", "name_en": "Bakhmach", "lat": 51.1827, "lon": 32.8291,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ряшки", "name_en": "Riashky", "lat": 50.6997, "lon": 32.5604,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мньов", "name_en": "Mnov", "lat": 51.4531, "lon": 30.656,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Срібне", "name_en": "Sribne", "lat": 50.6616, "lon": 32.9174,
     "region": "chernihiv", "aliases": []},
    # Ships with Коропʼє below: "короп" is a prefix of it, and the longest-stem rule
    # is what keeps the two 150 km apart.
    {"name_uk": "Короп", "name_en": "Korop", "lat": 51.5671, "lon": 32.9521,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Коропʼє", "name_en": "Koropie", "lat": 51.0278, "lon": 30.8336,
     "region": "chernihiv", "aliases": ["коропє"]},
    {"name_uk": "Оленівка", "name_en": "Olenivka", "lat": 51.2557, "lon": 32.3019,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Форостовичі", "name_en": "Forostovychi", "lat": 52.0203, "lon": 33.1129,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Тужар", "name_en": "Tuzhar", "lat": 51.1698, "lon": 30.6412,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Смолянка", "name_en": "Smolianka", "lat": 51.2456, "lon": 31.4603,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Рудка", "name_en": "Rudka", "lat": 51.5718, "lon": 31.1218,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Прилуки", "name_en": "Pryluky", "lat": 50.5951, "lon": 32.3867,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Пилипча", "name_en": "Pylypcha", "lat": 51.8689, "lon": 31.0374,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Петрушин", "name_en": "Petrushyn", "lat": 51.6486, "lon": 31.3503,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Льгів", "name_en": "Lhiv", "lat": 51.4943, "lon": 31.1476,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дроздовиця", "name_en": "Drozdovytsia", "lat": 51.9578, "lon": 31.4151,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Диханівка", "name_en": "Dykhanivka", "lat": 51.9512, "lon": 31.3931,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Басань", "name_en": "Basan", "lat": 50.5728, "lon": 31.5184,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Автуничі", "name_en": "Avtunychi", "lat": 52.0282, "lon": 31.653,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Михайло-Коцюбинське", "name_en": "Mykhailo-Kotsiubynske", "lat": 51.4502, "lon": 31.0793,
     "region": "chernihiv", "aliases": ["коцюбинське"]},
    {"name_uk": "Чернігів", "name_en": "Chernihiv", "lat": 51.4941, "lon": 31.2943,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Сновськ", "name_en": "Snovsk", "lat": 51.8188, "lon": 31.9449,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Корюківка", "name_en": "Koriukivka", "lat": 51.7745, "lon": 32.2513,
     "region": "chernihiv", "aliases": []},
    # Four letters, so the stemmer refuses to strip the ending and the stem stays
    # NOMINATIVE — the oblique forms must be aliases. Same trap as Ічня.
    {"name_uk": "Мена", "name_en": "Mena", "lat": 51.5228, "lon": 32.2164,
     "region": "chernihiv", "aliases": ["мену", "мени"]},
    {"name_uk": "Лосинівка", "name_en": "Losynivka", "lat": 50.8422, "lon": 31.917,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Сосниця", "name_en": "Sosnytsia", "lat": 51.5245, "lon": 32.5029,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Березна", "name_en": "Berezna", "lat": 51.5779, "lon": 31.7903,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Чемер", "name_en": "Chemer", "lat": 51.1002, "lon": 31.2122,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кукшин", "name_en": "Kukshyn", "lat": 51.1661, "lon": 31.6523,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Борсуків", "name_en": "Borsukiv", "lat": 51.0995, "lon": 30.976,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Зруб", "name_en": "Zrub", "lat": 51.1357, "lon": 31.6772,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хоробичі", "name_en": "Khorobychi", "lat": 52.0255, "lon": 31.5118,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Тупичів", "name_en": "Tupychiv", "lat": 51.7686, "lon": 31.436,
     "region": "chernihiv", "aliases": []},

    # These three name a village in BOTH oblasts and the text never says which —
    # the reporting channel's region does (DistrictMatcher(prefer_region=...)).
    {"name_uk": "Лебедівка", "name_en": "LebedivkaCH", "lat": 51.2309, "lon": 30.9683,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Рокитне", "name_en": "RokytneCH", "lat": 50.5673, "lon": 31.3601,
     "region": "chernihiv", "aliases": []},
    # Stems identically to Kyiv's Дніпровський raion; the tie-break is all there is.
    {"name_uk": "Дніпровське", "name_en": "DniprovskeCH", "lat": 51.3551, "lon": 30.6892,
     "region": "chernihiv", "aliases": []},


    # --- Чернігів city and its immediate ring ---
    {"name_uk": "Анисів", "name_en": "Anysiv", "lat": 51.4376, "lon": 31.3563,
     "region": "chernihiv", "aliases": []},
    # Beats Київська Березань by explaining more of the word. NOT region_only on
    # purpose: «Березанка» is no case form of «Березань», so a Kyiv channel typing
    # it means this village too.
    {"name_uk": "Березанка", "name_en": "Berezanka", "lat": 51.5509, "lon": 31.4394,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Білоус", "name_en": "Bilous", "lat": 51.515, "lon": 31.2,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Гущин", "name_en": "Hushchyn", "lat": 51.4498, "lon": 31.2261,
     "region": "chernihiv", "aliases": []},
    # Was landing on смт Десна, whose 4-char stem "десн" is the only one the word
    # reaches. Not region_only: hiding it would hand those messages back to Десна.
    {"name_uk": "Деснянка", "name_en": "Desnianka", "lat": 51.5678, "lon": 31.218,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Довжик", "name_en": "Dovzhyk", "lat": 51.6147, "lon": 31.0204,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Жукотки", "name_en": "Zhukotky", "lat": 51.5351, "lon": 31.0367,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Киїнка", "name_en": "Kyiinka", "lat": 51.4586, "lon": 31.194,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Левковичі", "name_en": "Levkovychi", "lat": 51.4941, "lon": 31.0868,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мохнатин", "name_en": "Mokhnatyn", "lat": 51.5891, "lon": 31.0632,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Павлівка", "name_en": "Pavlivka", "lat": 51.6389, "lon": 30.8969,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Пльохів", "name_en": "Pliokhiv", "lat": 51.5355, "lon": 30.9128,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Скоринець", "name_en": "Skorynets", "lat": 51.3158, "lon": 31.3073,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хмільниця", "name_en": "Khmilnytsia", "lat": 51.6453, "lon": 31.174,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Шестовиця", "name_en": "Shestovytsia", "lat": 51.3862, "lon": 31.1936,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Шибиринівка", "name_en": "Shybyrynivka", "lat": 51.5551, "lon": 30.9794,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ягідне", "name_en": "Yahidne", "lat": 51.3451, "lon": 31.2768,
     "region": "chernihiv", "aliases": []},


    # --- Northern and eastern approach villages ---
    {"name_uk": "Івангород", "name_en": "Ivanhorod", "lat": 51.0298, "lon": 32.4608,
     "region": "chernihiv", "aliases": []},
    # Vowel-final short name — inflection REPLACES the vowel, so «Ічню»/«Ічні» share
    # no stem with the nominative. Same trap as Мена.
    {"name_uk": "Ічня", "name_en": "Ichnia", "lat": 50.8623, "lon": 32.391,
     "region": "chernihiv", "aliases": ["ічню", "ічні"]},
    {"name_uk": "Бажанівка", "name_en": "Bazhanivka", "lat": 50.681, "lon": 31.9493,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бакланова Муравійка", "name_en": "Baklanova-Muraviika", "lat": 51.4122, "lon": 31.4422,
     "region": "chernihiv", "aliases": ["бакланов"]},
    {"name_uk": "Берестовець", "name_en": "Berestovets", "lat": 51.2581, "lon": 32.2092,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Блистова", "name_en": "Blystova", "lat": 51.8877, "lon": 32.9157,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Болотниця", "name_en": "Bolotnytsia", "lat": 50.8149, "lon": 32.9359,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бубнівщина", "name_en": "Bubnivshchyna", "lat": 50.3984, "lon": 32.2823,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бугринівка", "name_en": "Buhrynivka", "lat": 51.9825, "lon": 33.03,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бутівка", "name_en": "Butivka", "lat": 51.9321, "lon": 31.6752,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Буянки", "name_en": "Buianky", "lat": 51.7796, "lon": 31.1789,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Васьківці", "name_en": "Vaskivtsi", "lat": 50.7479, "lon": 32.8399,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Велике Устя", "name_en": "Velyke-Ustia", "lat": 51.4404, "lon": 32.5343,
     "region": "chernihiv", "aliases": ["устя"]},
    {"name_uk": "Великий Щимель", "name_en": "Velykyi-Shchymel", "lat": 51.7827, "lon": 31.9671,
     "region": "chernihiv", "aliases": ["щимель"]},
    # name_en, not name_uk, is what seed.py upserts on — a second "Vyshneve" would
    # silently overwrite the Kyiv town. Suffixed like DniprovskeCH.
    {"name_uk": "Вишневе", "name_en": "VyshneveCH", "lat": 51.7717, "lon": 31.218,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Воловиця", "name_en": "Volovytsia", "lat": 51.3662, "lon": 32.0787,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Галиця", "name_en": "Halytsia", "lat": 50.7465, "lon": 32.0282,
     "region": "chernihiv", "aliases": []},
    # The feed spells it «Голинка» (и), the village is «Голінка» (і).
    {"name_uk": "Голінка", "name_en": "Holinka", "lat": 51.0348, "lon": 33.0164,
     "region": "chernihiv", "aliases": ["голинка"]},
    {"name_uk": "Голубичі", "name_en": "Holubychi", "lat": 51.748, "lon": 31.1731,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дмитрівка", "name_en": "Dmytrivka", "lat": 50.9344, "lon": 32.9457,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Добропілля", "name_en": "Dobropillia", "lat": 51.4157, "lon": 32.6264,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Добрянка", "name_en": "Dobrianka", "lat": 52.0631, "lon": 31.1735,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дуболугівка", "name_en": "Duboluhivka", "lat": 51.2604, "lon": 32.0403,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дібрівне", "name_en": "Dibrivne", "lat": 51.7662, "lon": 31.6135,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Жукля", "name_en": "Zhuklia", "lat": 51.8081, "lon": 32.6634,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Задеріївка", "name_en": "Zaderiivka", "lat": 51.9125, "lon": 30.8517,
     "region": "chernihiv", "aliases": []},
    # The smt on the Ріпки line, not the same-named river 30 km south-east.
    {"name_uk": "Замглай", "name_en": "Zamhlai", "lat": 51.8124, "lon": 31.1631,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Заньки", "name_en": "Zanky", "lat": 51.1983, "lon": 31.9723,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Калюжинці", "name_en": "Kaliuzhyntsi", "lat": 50.694, "lon": 32.7434,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Карильське", "name_en": "Karylske", "lat": 51.5071, "lon": 32.9932,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Клюси", "name_en": "Klyusy", "lat": 52.0766, "lon": 31.9304,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Козилівка", "name_en": "Kozylivka", "lat": 51.8843, "lon": 32.7104,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Комарівка", "name_en": "Komarivka", "lat": 51.5623, "lon": 30.6663,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Красилівка", "name_en": "Krasylivka", "lat": 51.2011, "lon": 31.2074,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Красносільське", "name_en": "Krasnosilske", "lat": 51.1982, "lon": 32.1083,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кучинівка", "name_en": "Kuchynivka", "lat": 51.7253, "lon": 31.8988,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ларинівка", "name_en": "Larynivka", "lat": 52.0045, "lon": 33.0177,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Липів Ріг", "name_en": "Lypiv-Rih", "lat": 51.0775, "lon": 31.9541,
     "region": "chernihiv", "aliases": ["липів"]},
    {"name_uk": "Лиски", "name_en": "Lyski", "lat": 50.5934, "lon": 32.711,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Макошине", "name_en": "Makoshyne", "lat": 51.46, "lon": 32.3396,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Максаки", "name_en": "Maksaky", "lat": 51.4243, "lon": 32.1886,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Макіївка", "name_en": "Makiivka", "lat": 50.6765, "lon": 31.8284,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Манжосівка", "name_en": "Manzhosivka", "lat": 50.6089, "lon": 32.4576,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Митченки", "name_en": "Mytchenky", "lat": 51.2849, "lon": 32.9439,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Містки", "name_en": "Mistky", "lat": 52.0104, "lon": 32.0488,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Неданчичі", "name_en": "Nedanchychi", "lat": 51.5158, "lon": 30.6287,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Нехаївка", "name_en": "Nekhaivka", "lat": 51.4904, "lon": 32.8176,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Нові Млини", "name_en": "Novi-Mlyny", "lat": 51.4201, "lon": 32.7053,
     "region": "chernihiv", "aliases": ["млини"]},
    {"name_uk": "Омбиш", "name_en": "Ombysh", "lat": 51.0552, "lon": 32.3165,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Орлівка", "name_en": "Orlivka", "lat": 51.9138, "lon": 32.8162,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Охрамієвичі", "name_en": "Okhramiievychi", "lat": 51.9095, "lon": 32.2788,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Пекурівка", "name_en": "Pekurivka", "lat": 51.8131, "lon": 31.5876,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Перепис", "name_en": "Perepys", "lat": 52.0563, "lon": 31.458,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Переходівка", "name_en": "Perekhodivka", "lat": 51.2007, "lon": 31.5404,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Пручаї", "name_en": "Pruchai", "lat": 50.6726, "lon": 32.7253,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Півнівщина", "name_en": "Pivnivshchyna", "lat": 51.842, "lon": 31.6358,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Рогізки", "name_en": "Rohizky", "lat": 51.6889, "lon": 31.8684,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Семенівка", "name_en": "Semenivka", "lat": 52.1785, "lon": 32.5776,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Сидорівка", "name_en": "Sydorivka", "lat": 51.3322, "lon": 32.1604,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Смолигівка", "name_en": "Smolyhivka", "lat": 51.6749, "lon": 30.748,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Смоляж", "name_en": "Smoliazh", "lat": 51.2135, "lon": 32.0502,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Софіївка", "name_en": "Sofiivka", "lat": 51.884, "lon": 32.1388,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Стодоли", "name_en": "Stodoly", "lat": 51.1995, "lon": 31.5961,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Титівка", "name_en": "Tytivka", "lat": 51.2208, "lon": 31.8646,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Тростянець", "name_en": "Trostianets", "lat": 50.6646, "lon": 32.8567,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Турівка", "name_en": "Turivka", "lat": 51.874, "lon": 32.2291,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ушня", "name_en": "Ushnia", "lat": 51.4074, "lon": 32.0639,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Халимонове", "name_en": "Khalymonove", "lat": 51.2028, "lon": 32.914,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ховми", "name_en": "Khovmy", "lat": 51.3582, "lon": 32.2369,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Холми", "name_en": "Kholmy", "lat": 51.8726, "lon": 32.5956,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Яблунівка", "name_en": "Yablunivka", "lat": 50.4592, "lon": 32.1845,
     "region": "chernihiv", "aliases": []},


    # --- Region-exclusive landmarks (see region_only) ---
    # J3: both oblasts call their own plant «ТЕЦ», their own station «вокзал» and
    # their own airfield «летовище». `region_only` is what lets both sides exist
    # at once — each is visible only to a channel reporting from its own region.
    {"name_uk": "ТЕЦ", "name_en": "Chernihiv CHP", "lat": 51.4519, "lon": 31.2661,
     "region": "chernihiv", "region_only": True, "aliases": ["тец"]},
    {"name_uk": "Вокзал", "name_en": "Chernihiv Station", "lat": 51.4858, "lon": 31.2672,
     "region": "chernihiv", "region_only": True, "aliases": ["жд вокзал"]},
    {"name_uk": "Летовище", "name_en": "Chernihiv Airfield", "lat": 51.4055, "lon": 31.1511,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Очисні", "name_en": "Chernihiv Water Works", "lat": 51.5001, "lon": 31.3316,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Чексіл", "name_en": "Cheksil", "lat": 51.469, "lon": 31.2576,
     "region": "chernihiv", "region_only": True, "aliases": []},
    # NOT region_only: a Kyiv landmark only. It was on the Chernihiv candidate list
    # by mistake, and the per-channel sweep is what caught it.
    {"name_uk": "Рембаза", "name_en": "Rembaza", "lat": 50.4479, "lon": 30.6827,
     "aliases": ["рембазу", "рембази"]},
    {"name_uk": "Лемешівка", "name_en": "Lemeshivka", "lat": 52.0783, "lon": 31.6382,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Деревини", "name_en": "Derevyny", "lat": 52.1037, "lon": 31.5074,
     "region": "chernihiv", "aliases": []},

    {"name_uk": "Автозавод", "name_en": "Avtozavod", "lat": 51.5397, "lon": 31.2522,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Анновка", "name_en": "Annovka", "lat": 51.9441, "lon": 31.0875,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Атюша", "name_en": "Atiusha", "lat": 51.4243, "lon": 32.9906,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Батурин", "name_en": "Baturyn", "lat": 51.3413, "lon": 32.8778,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Берилівка", "name_en": "Berylivka", "lat": 52.0725, "lon": 31.7392,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бігач", "name_en": "Bihach", "lat": 51.6212, "lon": 31.6466,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Брусилів", "name_en": "BrusylivCH", "lat": 51.5426, "lon": 31.5171,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Буда", "name_en": "BudaCH", "lat": 51.7427, "lon": 32.109,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Ваганичі", "name_en": "Vahanychi", "lat": 52.024, "lon": 31.4346,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Варва", "name_en": "Varva", "lat": 50.4983, "lon": 32.7229,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Велички", "name_en": "Velychky", "lat": 51.6156, "lon": 30.7792,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Вертеча", "name_en": "Vertecha", "lat": 51.5871, "lon": 30.8328,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Вознесенське", "name_en": "Voznesenske", "lat": 51.5248, "lon": 31.4339,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Галайбине", "name_en": "Halaibyne", "lat": 51.3879, "lon": 32.576,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Гірманка", "name_en": "Hirmanka", "lat": 51.5193, "lon": 30.9862,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дачне", "name_en": "DachneCH", "lat": 51.8826, "lon": 32.7839,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Дігтярі", "name_en": "Dihtiari", "lat": 50.5819, "lon": 32.77,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Жавинка", "name_en": "Zhavynka", "lat": 51.4418, "lon": 31.2502,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Зайці", "name_en": "Zaitsi", "lat": 51.4689, "lon": 31.1239,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Залісся", "name_en": "ZalissiaCH", "lat": 51.8517, "lon": 31.252,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Замістя", "name_en": "Zamistia", "lat": 50.6116, "lon": 32.4244,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Іванівка", "name_en": "IvanivkaCH", "lat": 51.9142, "lon": 32.0972,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Киселівка", "name_en": "Kyselivka", "lat": 51.5343, "lon": 31.4462,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кинашівка", "name_en": "Kynashivka", "lat": 51.2863, "lon": 32.4059,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Клубівка", "name_en": "Klubivka", "lat": 51.9715, "lon": 30.9427,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Козероги", "name_en": "Kozerohy", "lat": 51.312, "lon": 31.036,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Конятин", "name_en": "Koniatyn", "lat": 51.5935, "lon": 32.7894,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Костючки", "name_en": "Kostiuchky", "lat": 51.7027, "lon": 32.26,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кучугури", "name_en": "Kuchuhury", "lat": 51.861, "lon": 32.468,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ладан", "name_en": "Ladan", "lat": 50.5136, "lon": 32.5877,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Левоньки", "name_en": "Levonky", "lat": 51.5633, "lon": 31.0323,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Лемеші", "name_en": "Lemeshi", "lat": 50.9921, "lon": 31.1355,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Лоска", "name_en": "Loska", "lat": 51.8503, "lon": 32.8951,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Лукнів", "name_en": "Lukniv", "lat": 51.5915, "lon": 33.1457,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Маховики", "name_en": "Makhovyky", "lat": 51.7795, "lon": 32.149,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Масани", "name_en": "Masany", "lat": 51.5207, "lon": 31.2275,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мекшунівка", "name_en": "Mekshunivka", "lat": 51.5659, "lon": 30.7898,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мохначі", "name_en": "Mokhnachi", "lat": 51.7353, "lon": 30.7813,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Наумівка", "name_en": "NaumivkaCH", "lat": 51.8369, "lon": 32.1948,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Новоселівка", "name_en": "NovoselivkaCH", "lat": 51.5309, "lon": 31.3851,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Нові Яриловичі", "name_en": "Novi-Yarylovychi", "lat": 52.0295, "lon": 31.003,
     "region": "chernihiv", "aliases": ["яриловичі"]},
    {"name_uk": "Обмачів", "name_en": "Obmachiv", "lat": 51.3724, "lon": 32.8179,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Олександрівка Друга", "name_en": "Oleksandrivka-Druha", "lat": 51.951, "lon": 30.9515,
     "region": "chernihiv", "region_only": True, "aliases": ["олександрівка"]},
    {"name_uk": "Піски", "name_en": "PiskyCH", "lat": 51.1506, "lon": 32.6622,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Подусівка", "name_en": "Podusivka", "lat": 51.4976, "lon": 31.2495,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Попільня", "name_en": "PopilniaCH", "lat": 51.7291, "lon": 32.0389,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Прачі", "name_en": "Prachi", "lat": 51.3655, "lon": 32.4464,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Розсудів", "name_en": "Rozsudiv", "lat": 51.6553, "lon": 30.7473,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Сахнівка", "name_en": "Sakhnivka", "lat": 51.6562, "lon": 31.7333,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Селянська Слобода", "name_en": "Selianska-Sloboda", "lat": 51.542, "lon": 31.0762,
     "region": "chernihiv", "aliases": ["селянська"]},
    {"name_uk": "Сухополова", "name_en": "Sukhopolova", "lat": 50.6324, "lon": 32.3799,
     "region": "chernihiv", "aliases": ["сухополівка"]},
    {"name_uk": "Сядрине", "name_en": "Siadryne", "lat": 51.8311, "lon": 32.4437,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Травневе", "name_en": "Travneve", "lat": 51.932, "lon": 31.4714,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Трисвятська Слобода", "name_en": "Trysviatska-Sloboda", "lat": 51.4703, "lon": 31.2085,
     "region": "chernihiv", "aliases": ["трисвятська"]},
    {"name_uk": "Тростянка", "name_en": "Trostianka", "lat": 51.3288, "lon": 32.6812,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Тур'я", "name_en": "Turia", "lat": 51.9018, "lon": 31.9932,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хвилівка", "name_en": "Khvylivka", "lat": 50.9793, "lon": 31.881,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хімволокно", "name_en": "Khimvolokno", "lat": 51.4637, "lon": 31.247,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Чепелів", "name_en": "Chepeliv", "lat": 51.8658, "lon": 32.0832,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Шмаївка", "name_en": "Shmaivka", "lat": 51.3749, "lon": 30.6762,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Ялівщина", "name_en": "Yalivshchyna", "lat": 51.5238, "lon": 31.3006,
     "region": "chernihiv", "aliases": []},

    {"name_uk": "Богданове", "name_en": "Bohdanove", "lat": 52.3082, "lon": 33.2745,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Бобрик", "name_en": "Bobryk", "lat": 51.1352, "lon": 31.7841,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Вересоч", "name_en": "Veresoch", "lat": 51.311, "lon": 31.7905,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Вовчок", "name_en": "Vovchok", "lat": 51.1599, "lon": 31.0424,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Волосківці", "name_en": "Voloskivtsi", "lat": 51.5482, "lon": 32.0066,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Городище", "name_en": "HorodyshcheCH", "lat": 51.271, "lon": 32.7983,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Держанівка", "name_en": "Derzhanivka", "lat": 51.0662, "lon": 31.3323,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Костобобрів", "name_en": "Kostobobriv", "lat": 52.2311, "lon": 32.915,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кунашівка", "name_en": "Kunashivka", "lat": 51.0473, "lon": 32.0085,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Локнисте", "name_en": "Loknyste", "lat": 51.5248, "lon": 31.7113,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Маличина Гребля", "name_en": "Malychyna-Hreblia", "lat": 51.3192, "lon": 32.4776,
     "region": "chernihiv", "aliases": ["маличина"]},
    {"name_uk": "Прогрес", "name_en": "Prohres", "lat": 51.122, "lon": 31.1772,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Стольне", "name_en": "Stolne", "lat": 51.5139, "lon": 31.9153,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Хатилова Гута", "name_en": "Khatylova-Huta", "lat": 51.3072, "lon": 30.6924,
     "region": "chernihiv", "aliases": ["хатилова"]},

    {"name_uk": "Деснянське", "name_en": "Desnianske CH", "lat": 51.7941, "lon": 33.0583,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Мезин", "name_en": "Mezyn", "lat": 51.8235, "lon": 33.0719,
     "region": "chernihiv", "aliases": []},
    # region_only, and the one case `prefer_region` cannot fix: "оболонн" explains
    # MORE of «над Оболонню» than Kyiv's own «оболон», so specificity hands the
    # Kyiv raion to this village. It ate six Kyiv callouts before this flag.
    {"name_uk": "Оболоння", "name_en": "Obolonnia", "lat": 51.6202, "lon": 32.9292,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Чайкине", "name_en": "Chaikyne", "lat": 52.1682, "lon": 32.9981,
     "region": "chernihiv", "aliases": []},

    {"name_uk": "Мазепи", "name_en": "Mazepy St CH", "lat": 51.4938, "lon": 31.2816,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Шевченка", "name_en": "Shevchenka St CH", "lat": 51.4935, "lon": 31.3048,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Полуботка", "name_en": "Polubotka St CH", "lat": 51.5055, "lon": 31.3201,
     "region": "chernihiv", "region_only": True, "aliases": ["полуботки"]},
    {"name_uk": "Кільцева", "name_en": "Kiltseva St CH", "lat": 51.5299, "lon": 31.3161,
     "region": "chernihiv", "region_only": True, "aliases": []},
    {"name_uk": "Епіцентр", "name_en": "Epicentr CH", "lat": 51.4987, "lon": 31.2537,
     "region": "chernihiv", "region_only": True, "aliases": []},
    # Ships with Лісконоги: «Лісконоги на мамекине» is a vector between two
    # neighbours 5 km apart, readable only if both exist.
    {"name_uk": "Мамекине", "name_en": "Mamekyne", "lat": 52.104, "lon": 33.2281,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Лісконоги", "name_en": "Liskonohy", "lat": 52.1365, "lon": 33.2765,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Брагинці", "name_en": "Brahyntsi", "lat": 50.5314, "lon": 32.9703,
     "region": "chernihiv", "aliases": []},

    # Both stations are region_only, so each channel sees its own. «Вокзальна
    # площа» keeps its own callouts — longer stem, more specific.
    {"name_uk": "Вокзал", "name_en": "Kyiv Station", "lat": 50.4404, "lon": 30.4894,
     "region": "kyiv", "region_only": True, "aliases": []},

    # Ships ONLY because matcher._is_airbase_reference exists: «аеродром «Українка»»
    # is a Russian bomber base in Amur Oblast, named in 20+ stored reports. Do not
    # remove one without the other.
    {"name_uk": "Українка", "name_en": "Ukrainka", "lat": 50.1537, "lon": 30.7421,
     "region": "kyiv", "aliases": ["українки", "українку"]},

    {"name_uk": "Смяч", "name_en": "Smiach", "lat": 52.1365, "lon": 33.1882,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Машеве", "name_en": "Masheve", "lat": 52.0865, "lon": 32.7975,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Лизунівка", "name_en": "Lyzunivka", "lat": 52.0694, "lon": 32.9257,
     "region": "chernihiv", "aliases": []},
    # The channel types both «Гремʼяч» and «Гремяч»; normalize() strips the apostrophe.
    {"name_uk": "Гремʼяч", "name_en": "Hremiach", "lat": 52.3393, "lon": 33.2908,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Муравʼї", "name_en": "Muravi", "lat": 52.3413, "lon": 33.3689,
     "region": "chernihiv", "aliases": []},
    # The name contains the stem "горіл", which _AFTERMATH used to suppress as
    # post-strike fire news — fixed at both ends (see parsing/vocab.py).
    {"name_uk": "Погорільці", "name_en": "Pohoriltsi", "lat": 52.0402, "lon": 32.5123,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Араповичі", "name_en": "Arapovychi", "lat": 51.9495, "lon": 33.3109,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Гмирянка", "name_en": "Hmyrianka", "lat": 50.7936, "lon": 32.4334,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Линовиця", "name_en": "Lynovytsia", "lat": 50.4641, "lon": 32.3963,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Дрімайлівка", "name_en": "Drimailivka", "lat": 51.2685, "lon": 31.8516,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Печенюги", "name_en": "Pecheniuhy", "lat": 52.0542, "lon": 33.0065,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Івківці", "name_en": "Ivkivtsi", "lat": 50.5316, "lon": 32.4902,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Кудлаївка", "name_en": "Kudlaivka", "lat": 51.9056, "lon": 33.1001,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Райгородок", "name_en": "Raihorodok", "lat": 51.6289, "lon": 33.0954,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Фаївка", "name_en": "Faivka", "lat": 51.9928, "lon": 32.9361,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Парафіївка", "name_en": "Parafiivka", "lat": 50.884, "lon": 32.6447,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Здрягівка", "name_en": "Zdriahivka", "lat": 51.9289, "lon": 31.7495,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Перелюб", "name_en": "Pereliub", "lat": 51.9835, "lon": 32.33,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Григорівка", "name_en": "Hryhorivka", "lat": 51.0377, "lon": 32.8567,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Курилівка", "name_en": "Kurylivka", "lat": 50.9563, "lon": 31.9726,
     "region": "chernihiv", "aliases": []},
    # A named area INSIDE Чернігів, not a village — the spotters warn the city from
    # it the way Kyiv channels use Троєщина.
    {"name_uk": "Яцево", "name_en": "Yatsevo", "lat": 51.5375, "lon": 31.3636,
     "region": "chernihiv", "aliases": []},
    {"name_uk": "Терехівка", "name_en": "Terekhivka", "lat": 51.5945, "lon": 31.4066,
     "region": "chernihiv", "aliases": []},

    # --- Сумщина (2026-08-28) --------------------------------------------
    # The region's first entries: 0.38.0 shipped it declared and EMPTY, so all
    # 3760 mined messages of its two spotter channels localized to nothing.
    # Mined and swept per GAZETTEER.md; the notes below are only the lines
    # whose shape is not self-evident.
    # `region_only`, like Глухів below: a KYIV channel writes «Суми» only as
    # somewhere else — «Ціль на Суми», «по трасі Київ-Суми», an X-101 flight-time
    # table. All 12 such stored messages would have become a live target 350 km
    # away. A Сумщина channel writing it means the city, and that one still
    # matches. The stem is whole-word (see vocab): as a prefix it swallows
    # Сумихімпром, which is a target of its own.
    {"name_uk": "Суми", "name_en": "Sumy", "lat": 50.912, "lon": 34.8028,
     "region": "sumy", "region_only": True, "aliases": ["сум", "сумах", "сумами"]},
    {"name_uk": "Тростянець", "name_en": "Trostianets SM", "lat": 50.4805, "lon": 34.9647,
     "region": "sumy", "aliases": []},
    {"name_uk": "Охтирка", "name_en": "Okhtyrka", "lat": 50.3115, "lon": 34.8869,
     "region": "sumy", "aliases": []},
    {"name_uk": "Лебедин", "name_en": "Lebedyn", "lat": 50.581, "lon": 34.4753,
     "region": "sumy", "aliases": []},
    {"name_uk": "Білопілля", "name_en": "Bilopillia", "lat": 51.146, "lon": 34.3122,
     "region": "sumy", "aliases": []},
    {"name_uk": "Краснопілля", "name_en": "Krasnopillia", "lat": 50.7713, "lon": 35.2563,
     "region": "sumy", "aliases": []},
    {"name_uk": "Миропілля", "name_en": "Myropillia", "lat": 51.0273, "lon": 35.247,
     "region": "sumy", "aliases": []},
    {"name_uk": "Ромни", "name_en": "Romny", "lat": 50.7421, "lon": 33.4877,
     "region": "sumy", "aliases": []},
    {"name_uk": "Недригайлів", "name_en": "Nedryhailiv", "lat": 50.8359, "lon": 33.8783,
     "region": "sumy", "aliases": []},
    {"name_uk": "Липова Долина", "name_en": "Lypova Dolyna", "lat": 50.5638, "lon": 33.799,
     "region": "sumy", "aliases": ["липов"]},
    {"name_uk": "Конотоп", "name_en": "Konotop", "lat": 51.2397, "lon": 33.2067,
     "region": "sumy", "aliases": []},
    {"name_uk": "Кролевець", "name_en": "Krolevets", "lat": 51.5549, "lon": 33.3876,
     "region": "sumy", "aliases": []},
    {"name_uk": "Путивль", "name_en": "Putyvl", "lat": 51.336, "lon": 33.8715,
     "region": "sumy", "aliases": []},
    {"name_uk": "Буринь", "name_en": "Buryn", "lat": 51.196, "lon": 33.8288,
     "region": "sumy", "aliases": []},
    {"name_uk": "Дубов'язівка", "name_en": "Dubovyazivka", "lat": 51.1325, "lon": 33.3785,
     "region": "sumy", "aliases": []},
    # "глух" is inside «глухий»/«глухо» — zero corpus hits across 13.6k messages,
    # but «глухий вибух» is a phrase this genre plausibly types, so re-sweep if
    # the feed changes. `region_only` because a Kyiv channel names the town as
    # elsewhere (1 stored message).
    {"name_uk": "Глухів", "name_en": "Hlukhiv", "lat": 51.6783, "lon": 33.9093,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Шостка", "name_en": "Shostka", "lat": 51.8644, "lon": 33.4729,
     "region": "sumy", "aliases": []},
    {"name_uk": "Ямпіль", "name_en": "Yampil SM", "lat": 51.9481, "lon": 33.7785,
     "region": "sumy", "aliases": []},
    {"name_uk": "Свеса", "name_en": "Svesa", "lat": 51.9482, "lon": 33.933,
     "region": "sumy", "aliases": []},
    {"name_uk": "Середина-Буда", "name_en": "Seredyna-Buda", "lat": 52.1887, "lon": 34.0306,
     "region": "sumy", "aliases": ["середино", "серединобуд"]},
    {"name_uk": "Есмань", "name_en": "Esman", "lat": 51.7672, "lon": 34.0635,
     "region": "sumy", "aliases": []},
    {"name_uk": "Вороніж", "name_en": "Voronizh SM", "lat": 51.7778, "lon": 33.466,
     "region": "sumy", "aliases": []},
    {"name_uk": "Ворожба", "name_en": "Vorozhba", "lat": 51.1722, "lon": 34.2245,
     "region": "sumy", "aliases": []},
    {"name_uk": "Терни", "name_en": "Terny SM", "lat": 50.9941, "lon": 33.9835,
     "region": "sumy", "aliases": []},
    {"name_uk": "Чупахівка", "name_en": "Chupakhivka", "lat": 50.3799, "lon": 34.5845,
     "region": "sumy", "aliases": []},
    {"name_uk": "Кириківка", "name_en": "Kyrykivka", "lat": 50.3485, "lon": 35.1304,
     "region": "sumy", "aliases": []},
    {"name_uk": "Велика Писарівка", "name_en": "Velyka Pysarivka", "lat": 50.4253, "lon": 35.4839,
     "region": "sumy", "aliases": ["великописарівськ"]},
    {"name_uk": "Боромля", "name_en": "Boromlia", "lat": 50.6195, "lon": 34.9671,
     "region": "sumy", "aliases": []},
    {"name_uk": "Улянівка", "name_en": "Ulianivka SM", "lat": 50.9748, "lon": 34.2938,
     "region": "sumy", "aliases": []},
    {"name_uk": "Штепівка", "name_en": "Shtepivka", "lat": 50.7964, "lon": 34.3401,
     "region": "sumy", "aliases": []},
    {"name_uk": "Чернеча Слобода", "name_en": "Chernecha Sloboda", "lat": 51.0651, "lon": 33.601,
     "region": "sumy", "aliases": ["чернеч"]},
    {"name_uk": "Шалигине", "name_en": "Shalyhyne", "lat": 51.5757, "lon": 34.0998,
     "region": "sumy", "aliases": []},
    # The border belt of Сумський район — the КАБ/FPV traffic, and the only
    # part of this region where a callout is minutes rather than tens of
    # minutes from an impact.
    {"name_uk": "Хотінь", "name_en": "Khotin", "lat": 51.0787, "lon": 34.78,
     "region": "sumy", "aliases": []},
    {"name_uk": "Юнаківка", "name_en": "Yunakivka", "lat": 51.1227, "lon": 35.0323,
     "region": "sumy", "aliases": []},
    {"name_uk": "Стецьківка", "name_en": "Stetskivka", "lat": 51.0099, "lon": 34.7769,
     "region": "sumy", "aliases": []},
    {"name_uk": "Могриця", "name_en": "Mohrytsia", "lat": 51.035, "lon": 35.1035,
     "region": "sumy", "aliases": []},
    {"name_uk": "Вакалівщина", "name_en": "Vakalivshchyna", "lat": 51.0287, "lon": 34.9303,
     "region": "sumy", "aliases": []},
    {"name_uk": "Храпівщина", "name_en": "Khrapivshchyna", "lat": 51.0796, "lon": 34.9571,
     "region": "sumy", "aliases": ["храпівщін"]},
    {"name_uk": "Мар'їне", "name_en": "Mariine", "lat": 51.0747, "lon": 34.9857,
     "region": "sumy", "aliases": []},
    {"name_uk": "Писарівка", "name_en": "Pysarivka SM", "lat": 51.0799, "lon": 34.8342,
     "region": "sumy", "region_only": True, "aliases": []},
    # Whole-word (see vocab): the stem "річк" also fires on «річка», which cost a
    # pin on the Kyiv feed's «річка "Либідь" пофарбувалася». The hromada
    # adjective «Річківської» is a separate, longer alias and needs no guard.
    {"name_uk": "Річки", "name_en": "Richky", "lat": 51.1202, "lon": 34.4952,
     "region": "sumy", "aliases": ["річківськ"]},
    {"name_uk": "Баранівка", "name_en": "Baranivka SM", "lat": 50.9422, "lon": 34.84,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Битиця", "name_en": "Bytytsia", "lat": 50.9999, "lon": 34.9376,
     "region": "sumy", "aliases": []},
    {"name_uk": "Біловоди", "name_en": "Bilovody", "lat": 51.1719, "lon": 34.9739,
     "region": "sumy", "aliases": []},
    {"name_uk": "Радьківка", "name_en": "Radkivka", "lat": 51.0136, "lon": 34.8287,
     "region": "sumy", "aliases": []},
    {"name_uk": "Низи", "name_en": "Nyzy", "lat": 50.7799, "lon": 34.7793,
     "region": "sumy", "aliases": []},
    {"name_uk": "Степанівка", "name_en": "Stepanivka SM", "lat": 50.9417, "lon": 34.6422,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Угроїди", "name_en": "Uhroidy", "lat": 50.8598, "lon": 35.2703,
     "region": "sumy", "aliases": []},
    {"name_uk": "Жигайлівка", "name_en": "Zhyhailivka", "lat": 50.632, "lon": 35.1006,
     "region": "sumy", "aliases": []},
    {"name_uk": "Садки", "name_en": "Sadky SM", "lat": 51.0986, "lon": 35.0933,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Пушкарівка", "name_en": "Pushkarivka", "lat": 50.9929, "lon": 34.9219,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Липняк", "name_en": "Lypniak", "lat": 50.9464, "lon": 34.8836,
     "region": "sumy", "aliases": []},
    {"name_uk": "Іволжанське", "name_en": "Ivolzhanske", "lat": 51.0693, "lon": 34.8744,
     "region": "sumy", "aliases": []},
    {"name_uk": "Бездрик", "name_en": "Bezdryk", "lat": 50.867, "lon": 34.9477,
     "region": "sumy", "aliases": []},
    # «старе» counts only before «село» (vocab._ALIAS_NEXT_WORD_REQUIRED) — on
    # its own it is an ordinary adjective. Same shape as Зелений Гай and
    # Блакитні Озера: a spaced name whose second word is too generic to carry it.
    {"name_uk": "Старе Село", "name_en": "Stare Selo SM", "lat": 50.8276, "lon": 34.8085,
     "region": "sumy", "region_only": True, "aliases": ["старе"]},
    {"name_uk": "Вільшанка", "name_en": "Vilshanka SM", "lat": 50.9741, "lon": 34.987,
     "region": "sumy", "region_only": True, "aliases": ["ольшанк"]},
    {"name_uk": "Вільшана", "name_en": "Vilshana SM", "lat": 50.8197, "lon": 34.0228,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Кровне", "name_en": "Krovne", "lat": 51.049, "lon": 34.7113,
     "region": "sumy", "aliases": []},
    {"name_uk": "Варачине", "name_en": "Varachyne", "lat": 51.1414, "lon": 34.9238,
     "region": "sumy", "aliases": []},
    {"name_uk": "Хомине", "name_en": "Khomyne", "lat": 50.9598, "lon": 34.8591,
     "region": "sumy", "aliases": []},
    {"name_uk": "Бранцівка", "name_en": "Brantsivka", "lat": 50.6057, "lon": 35.2019,
     "region": "sumy", "aliases": []},
    {"name_uk": "Криничне", "name_en": "Krynychne SM", "lat": 50.5494, "lon": 35.0561,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Глибне", "name_en": "Hlybne", "lat": 50.8265, "lon": 35.0799,
     "region": "sumy", "aliases": []},
    {"name_uk": "Сінне", "name_en": "Sinne", "lat": 50.9642, "lon": 35.0859,
     "region": "sumy", "aliases": []},
    {"name_uk": "Басівка", "name_en": "Basivka SM", "lat": 51.1811, "lon": 35.0879,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Руднівка", "name_en": "Rudnivka SM", "lat": 51.0267, "lon": 34.7347,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Яструбине", "name_en": "Yastrubyne", "lat": 51.139, "lon": 34.6169,
     "region": "sumy", "aliases": []},
    {"name_uk": "Самотоївка", "name_en": "Samotoivka", "lat": 50.8107, "lon": 35.148,
     "region": "sumy", "aliases": []},
    {"name_uk": "Косівщина", "name_en": "Kosivshchyna", "lat": 50.9115, "lon": 34.7241,
     "region": "sumy", "aliases": []},
    {"name_uk": "Яблунівка", "name_en": "Yablunivka SM", "lat": 51.142, "lon": 34.9739,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Спаське", "name_en": "Spaske SM", "lat": 51.0744, "lon": 34.6395,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Томашівка", "name_en": "Tomashivka SM", "lat": 50.9058, "lon": 33.6449,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Мутин", "name_en": "Mutyn", "lat": 51.4225, "lon": 33.4808,
     "region": "sumy", "aliases": []},
    {"name_uk": "Микільське", "name_en": "Mykilske SM", "lat": 51.0222, "lon": 34.9947,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Біжівка", "name_en": "Bizhivka", "lat": 51.0038, "lon": 33.7676,
     "region": "sumy", "aliases": []},
    {"name_uk": "Великий Вистороп", "name_en": "Vystorop", "lat": 50.6952, "lon": 34.7847,
     "region": "sumy", "aliases": ["вистороп"]},
    {"name_uk": "Ганнівка", "name_en": "Hannivka SM", "lat": 50.9434, "lon": 34.7306,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Андріївка", "name_en": "Andriivka SM", "lat": 51.1287, "lon": 34.8246,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Правдюки", "name_en": "Pravdiuky", "lat": 50.7822, "lon": 33.6896,
     "region": "sumy", "aliases": []},
    {"name_uk": "Валки", "name_en": "Valky SM", "lat": 50.7771, "lon": 34.6461,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Верхня Пожня", "name_en": "Verkhnia Pozhnia", "lat": 50.5659, "lon": 35.3513,
     "region": "sumy", "aliases": ["пожн"]},
    {"name_uk": "Гриценкове", "name_en": "Hrytsenkove", "lat": 50.9725, "lon": 34.7058,
     "region": "sumy", "aliases": []},
    {"name_uk": "Коршачина", "name_en": "Korshachyna", "lat": 51.0161, "lon": 34.4994,
     "region": "sumy", "aliases": []},
    {"name_uk": "Кардашівка", "name_en": "Kardashivka", "lat": 50.993, "lon": 34.7518,
     "region": "sumy", "aliases": []},
    {"name_uk": "Северинівка", "name_en": "Severynivka SM", "lat": 50.9898, "lon": 34.6588,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Житейське", "name_en": "Zhyteiske", "lat": 50.9818, "lon": 34.8287,
     "region": "sumy", "aliases": []},
    {"name_uk": "Климентове", "name_en": "Klymentove", "lat": 50.3823, "lon": 34.9248,
     "region": "sumy", "aliases": []},
    {"name_uk": "Кононенкове", "name_en": "Kononenkove", "lat": 50.9198, "lon": 34.6862,
     "region": "sumy", "aliases": []},
    {"name_uk": "Синяк", "name_en": "Syniak SM", "lat": 51.0522, "lon": 34.5008,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Попівка", "name_en": "Popivka SM", "lat": 51.2529, "lon": 33.1241,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Велика Рибиця", "name_en": "Velyka Rybytsia", "lat": 51.0085, "lon": 35.1766,
     "region": "sumy", "aliases": ["рибиц"]},
    {"name_uk": "Рогізне", "name_en": "Rohizne", "lat": 51.0019, "lon": 34.6834,
     "region": "sumy", "aliases": []},
    {"name_uk": "Велика Чернеччина", "name_en": "Velyka Chernechchyna", "lat": 50.9545, "lon": 34.9256,
     "region": "sumy", "aliases": ["чернеччин", "великочернеччин"]},
    {"name_uk": "Верхня Сироватка", "name_en": "Verkhnia Syrovatka", "lat": 50.8312, "lon": 34.9421,
     "region": "sumy", "aliases": ["сироватк"]},
    {"name_uk": "Токарі", "name_en": "Tokari SM", "lat": 50.92, "lon": 34.902,
     "region": "sumy", "aliases": []},
    {"name_uk": "Вири", "name_en": "Vyry", "lat": 51.0338, "lon": 34.4135,
     "region": "sumy", "aliases": []},
    {"name_uk": "Мезенівка", "name_en": "Mezenivka", "lat": 50.6308, "lon": 35.3135,
     "region": "sumy", "aliases": []},
    {"name_uk": "Собичеве", "name_en": "Sobycheve", "lat": 51.8163, "lon": 33.6982,
     "region": "sumy", "aliases": []},
    {"name_uk": "Воронцове", "name_en": "Vorontsove", "lat": 51.6784, "lon": 33.4598,
     "region": "sumy", "aliases": []},
    {"name_uk": "Кияниця", "name_en": "Kyianytsia", "lat": 51.0696, "lon": 34.9101,
     "region": "sumy", "aliases": []},
    {"name_uk": "Шпилівка", "name_en": "Shpylivka", "lat": 50.7948, "lon": 34.6892,
     "region": "sumy", "aliases": []},
    {"name_uk": "Миколаївка", "name_en": "Mykolaivka SM", "lat": 50.9395, "lon": 34.3729,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Лугівка", "name_en": "Luhivka SM", "lat": 50.4462, "lon": 35.4717,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Новоукраїнка", "name_en": "Novoukrainka SM", "lat": 50.4774, "lon": 35.1425,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Олександрівка", "name_en": "Oleksandrivka SM", "lat": 50.7302, "lon": 35.316,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Кіндратівка", "name_en": "Kindrativka", "lat": 51.142, "lon": 34.7715,
     "region": "sumy", "aliases": []},
    {"name_uk": "Мала Корчаківка", "name_en": "Mala Korchakivka", "lat": 51.099, "lon": 34.8717,
     "region": "sumy", "aliases": ["корчаківк"]},
    # One entry for the Великий/Малий pair, 4.5 km apart and never named in the
    # same message. `region_only` because Чернігівщина has its own Бобрик, also
    # `region_only` — the alias is all either of them can match on.
    {"name_uk": "Великий Бобрик", "name_en": "Velykyi Bobryk", "lat": 50.7668, "lon": 35.0275,
     "region": "sumy", "region_only": True, "aliases": ["бобрик"]},
    {"name_uk": "Грунівка", "name_en": "Hrunivka", "lat": 50.9941, "lon": 35.1075,
     "region": "sumy", "aliases": []},
    {"name_uk": "Капітанівка", "name_en": "Kapitanivka SM", "lat": 51.0905, "lon": 34.5857,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Земляне", "name_en": "Zemliane", "lat": 50.6851, "lon": 35.2915,
     "region": "sumy", "aliases": []},
    {"name_uk": "Ясенок", "name_en": "Yasenok", "lat": 50.7019, "lon": 35.1302,
     "region": "sumy", "aliases": []},
    {"name_uk": "Дернове", "name_en": "Dernove", "lat": 50.5045, "lon": 35.2604,
     "region": "sumy", "aliases": []},
    {"name_uk": "Паліївка", "name_en": "Paliivka", "lat": 51.9076, "lon": 33.6345,
     "region": "sumy", "aliases": []},
    {"name_uk": "Симонівка", "name_en": "Symonivka", "lat": 50.83, "lon": 34.617,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Комишанка", "name_en": "Komyshanka", "lat": 50.8396, "lon": 34.1404,
     "region": "sumy", "aliases": []},
    {"name_uk": "Барилівка", "name_en": "Barylivka", "lat": 50.9917, "lon": 35.0581,
     "region": "sumy", "aliases": []},
    {"name_uk": "Склярівка", "name_en": "Skliarivka", "lat": 51.0219, "lon": 34.6032,
     "region": "sumy", "aliases": []},
    {"name_uk": "Мозкове", "name_en": "Mozkove", "lat": 50.6916, "lon": 35.0666,
     "region": "sumy", "aliases": []},
    {"name_uk": "Постольне", "name_en": "Postolne", "lat": 51.0281, "lon": 34.5558,
     "region": "sumy", "aliases": []},
    {"name_uk": "Василівка", "name_en": "Vasylivka SM", "lat": 50.9, "lon": 34.8555,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Сад", "name_en": "Sad", "lat": 50.8817, "lon": 34.7109,
     "region": "sumy", "region_only": True, "aliases": ["сади"]},
    {"name_uk": "Зелений Гай", "name_en": "Zelenyi Hai SM", "lat": 50.9834, "lon": 34.8789,
     "region": "sumy", "region_only": True, "aliases": ["зелений"]},
    # Суми itself, at the granularity the spotters narrate a drone across it —
    # the same shape as the Kyiv channels' Троєщина/Оболонь layer and the
    # Chernihiv city layer. `region_only` on the generic ones: every oblast
    # centre has a Проспект Перемоги, a Зарічний район and a Тополя.
    {"name_uk": "Рибці", "name_en": "Rybtsi", "lat": 51.0037, "lon": 34.8572,
     "region": "sumy", "aliases": []},
    {"name_uk": "Піщане", "name_en": "Pishchane SM", "lat": 50.9855, "lon": 34.8109,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Баси", "name_en": "Basy", "lat": 50.8624, "lon": 34.8865,
     "region": "sumy", "aliases": []},
    {"name_uk": "Веретенівка", "name_en": "Veretenivka", "lat": 50.9436, "lon": 34.7461,
     "region": "sumy", "aliases": ["веретинівк"]},
    {"name_uk": "Тополя", "name_en": "Topolia", "lat": 50.9431, "lon": 34.8042,
     "region": "sumy", "region_only": True, "aliases": ["тополю"]},
    {"name_uk": "Тополянська", "name_en": "Topolianska St", "lat": 50.9532, "lon": 34.7972,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Проспект Перемоги", "name_en": "Peremohy Ave Sumy", "lat": 50.9376, "lon": 34.7847,
     "region": "sumy", "region_only": True, "aliases": ["перемоги"]},
    {"name_uk": "Героїв Крут", "name_en": "Heroiv Krut Sumy", "lat": 50.9168, "lon": 34.8339,
     "region": "sumy", "region_only": True, "aliases": ["крут"]},
    {"name_uk": "Лушпи", "name_en": "Lushpy Ave", "lat": 50.9152, "lon": 34.83,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Металургів", "name_en": "Metalurhiv St", "lat": 50.9262, "lon": 34.79,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Білопільський Шлях", "name_en": "Bilopilskyi Shliakh", "lat": 50.9349, "lon": 34.7395,
     "region": "sumy", "region_only": True, "aliases": ["білопільськ"]},
    {"name_uk": "Блакитні Озера", "name_en": "Blakytni Ozera", "lat": 50.9184, "lon": 34.8562,
     "region": "sumy", "region_only": True, "aliases": ["блакитні"]},
    {"name_uk": "Сумихімпром", "name_en": "Sumykhimprom", "lat": 50.8775, "lon": 34.8852,
     "region": "sumy", "region_only": True, "aliases": ["хімпром"]},
    {"name_uk": "Зарічний", "name_en": "Zarichnyi Sumy", "lat": 50.8809, "lon": 34.8211,
     "region": "sumy", "region_only": True, "aliases": []},
    {"name_uk": "Ковпаківський", "name_en": "Kovpakivskyi Sumy", "lat": 50.9764, "lon": 34.8685,
     "region": "sumy", "region_only": True, "aliases": []},


    # Sentinel for CITY-WIDE threats («ціль на місто»), NOT a matchable place:
    # DistrictMatcher skips it and the LLM never sees it. It exists only so a
    # city-wide event has a valid point and a name; the map renders those as a
    # banner. Detection is the parser's `citywide` flag.
    {"name_uk": "Київ", "name_en": CITYWIDE_NAME_EN,
     "lat": KYIV_CENTER["lat"], "lon": KYIV_CENTER["lon"], "aliases": []},
]


# Seed set of monitored sources. `channel_key` is the Telegram handle we'd
# subscribe to via Telethon later; `trust_weight` biases fusion confidence.
# The aggregator has a low weight because it mostly reposts the others.
# `extra_regions` widens what a channel may localize into beyond its primary
# `region` — a source never pins a place outside its bindings. The Kyiv spotter
# channels carry the northern approach as well as their own oblast, so they are
# bound to both; narrow or widen a real channel in /admin, not here.
SOURCES: list[dict] = [
    {"channel_key": "kyiv_ppo", "name": "Київ ППО монітор", "trust_weight": 1.0,
     "extra_regions": ["chernihiv"]},
    {"channel_key": "povitryanka", "name": "Повітряна тривога", "trust_weight": 1.0,
     "extra_regions": ["chernihiv"]},
    {"channel_key": "shahed_watch", "name": "Shahed Watch", "trust_weight": 0.8,
     "extra_regions": ["chernihiv"]},
    {"channel_key": "aggregator", "name": "Агрегатор (репости)", "trust_weight": 0.4,
     "extra_regions": ["chernihiv"]},
    # role='alert' -> routed through alert_parser.py, not the spotter parser
    # (see telegram_listener.py). Dormant unless ALERT_CHANNELS names it.
    # trust_weight is unused for an alert-role source (spotter fusion only).
    {"channel_key": "KyivCityOfficial", "name": "КМДА – офіційний канал",
     "trust_weight": 1.0, "role": "alert"},
]
