"""official_alerts

Adds the `alerts` table (official air-raid alert windows) and `sources.role`
so the ingest pipeline can route a channel's messages to the spotter parser
or the alert parser (app/alert_parser.py). Existing sources backfill to
role='spotter' — the only role that existed before this phase.

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-12 10:27:29.141824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('started_raw_id', sa.Integer(), nullable=True),
    sa.Column('ended_raw_id', sa.Integer(), nullable=True),
    sa.Column('closed_reason', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ended_raw_id'], ['raw_messages.id'], ),
    sa.ForeignKeyConstraint(['started_raw_id'], ['raw_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('role', sa.String(length=10), nullable=False, server_default='spotter')
        )

    # Drop the server_default now that existing rows are backfilled — new
    # rows get 'spotter' from the ORM-side mapped_column default.
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.alter_column('role', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('alerts')
    # ### end Alembic commands ###
